name: assignment9
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0-152.0.dev <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  audioplayers: ^4.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/arctic.jpg
    - assets/images/atl.jpg
    - assets/images/cte.jpg
    - assets/images/nd.jpg
    - assets/images/paramore.jpg
    - assets/images/ptv.jpg
    - assets/images/roc.jpg
    - assets/images/tame.jpg
    - assets/images/tyler.jpg
    - assets/images/mac.jpg
    - assets/images/
    - assets/songs/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: ZenDots-Regular
      fonts:
        - asset: assets/fonts/ZenDots-Regular.ttf
